# Site Settings
title: "ABHIRAM | BIOINFORMATICS"
name: "ABHIRAM S"
email: s.abhiramofficial@gmail.com
description: "Decoding life's source code through the lens of logic."
url: "https://rams-info-in.github.io"
baseurl: ""
locale: "en-US"
timezone: "Asia/Kolkata"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "neon"

enable_copy_code_button: true
breadcrumbs: true

# Formatting
markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

search: true

# Author Info
author:
  name: "ABHIRAM S"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Decoding life's source code through the lens of logic!"
  location: "Kerala, India"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:s.abhiramofficial@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rams-info-in"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
