# Site Settings
title: "ABHIRAM | BIOINFORMATICS"
description: "Decoding life’s source code through the lens of logic."
url: "https://rams-info-in.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "aqua"

# Formatting
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author Info
author:
  name: "ABHIRAM S"
  bio: "Decoding life’s source code through the lens of logic!"
  location: "Goa, India"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:s.abhiramofficial@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rams-info-in"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
